# Generated by Django 4.2 on 2023-05-30 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=12)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_num', models.PositiveIntegerField()),
                ('date_avail', models.DateField()),
                ('date_flight', models.DateField()),
                ('date_depart', models.DateTimeField()),
                ('date_land', models.DateTimeField()),
                ('destination', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_res', models.DateTimeField(auto_now_add=True)),
                ('date_acc', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customermodel')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ticketmodel')),
            ],
        ),
    ]
